const { createRequire } = require("module");
const path = require("path");
const require = createRequire(__dirname + "/");
const reactPdfPath = path.dirname(require.resolve("react-pdf/package.json"));
const pdfjsDistPath = path.dirname(require.resolve("pdfjs-dist/package.json", { paths: [reactPdfPath] }));
const { version } = require(path.join(pdfjsDistPath, "package.json"));
console.log("react-pdf's pdfjs-dist version:", version);
const myPdfjsDistPath = path.dirname(require.resolve("pdfjs-dist/package.json"));
const { version: myVersion } = require(path.join(myPdfjsDistPath, "package.json"));
console.log("my pdfjs-dist version:", myVersion);
