import { NextResponse, type NextRequest } from "next/server";
import { requirePermission, isAdminAuthError } from "@/lib/auth/requireAdmin";
import { rateLimit } from "@/lib/rate-limit";
import { getUsers } from "@/lib/admin/users";
import { usersExportSheet } from "@/lib/admin/users-export";
import {
  USER_SORT_OPTIONS,
  JOINED_RANGE_OPTIONS,
  JOINED_RANGE_LABELS,
  USER_SORT_LABELS,
  type UserSort,
  type JoinedRange,
} from "@/lib/admin/users-shared";
import { sheetsToCsv } from "@/lib/export/csv";
import { buildWorkbook } from "@/lib/export/xlsx";
import { EXPORT_MIME, exportFilename, parseExportFormat, type ExportContext } from "@/lib/export/core";

export const dynamic = "force-dynamic";

const MAX_SELECTED_IDS = 500;
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/**
 * GET /api/admin/users/export?format=csv|xlsx&q=…&role=…&status=…&joined=…&sort=…[&ids=…]
 *
 * Server-side export of the Users list. Honours the exact filters/sort the
 * page uses (via the same lib/admin/users query), or a set of selected row
 * ids. Auth: `users` permission (server-verified — never the client's word).
 * Exports the whole filtered result set, not just the visible page. Only
 * fields shown in the Users UI are included (lib/admin/users-export.ts) —
 * never password hashes, tokens, or auth metadata. Every export is audited.
 */
export async function GET(request: NextRequest) {
  try {
    const { userId, role: callerRole, supabase } = await requirePermission("users", "read");

    const { success } = await rateLimit(`users-export:${userId}`, 10, 60_000);
    if (!success) {
      return NextResponse.json({ error: "Too many exports. Try again shortly." }, { status: 429 });
    }

    const sp = request.nextUrl.searchParams;
    const format = parseExportFormat(sp.get("format"));

    // Same validation vocabulary as the Users page.
    const q = (sp.get("q") ?? "").trim().slice(0, 100);
    const roleFilter = (sp.get("role") ?? "").trim();
    const statusFilter = (sp.get("status") ?? "").trim();
    const joinedRaw = (sp.get("joined") ?? "").trim();
    const sortRaw = (sp.get("sort") ?? "").trim();
    const joined = (JOINED_RANGE_OPTIONS as readonly string[]).includes(joinedRaw)
      ? (joinedRaw as JoinedRange)
      : "all";
    const sort = (USER_SORT_OPTIONS as readonly string[]).includes(sortRaw)
      ? (sortRaw as UserSort)
      : "newest";

    const ids = (sp.get("ids") ?? "")
      .split(",")
      .map((s) => s.trim())
      .filter((s) => UUID_RE.test(s))
      .slice(0, MAX_SELECTED_IDS);

    // Whole filtered result set (the users query is capped at 2000 candidates).
    const result = await getUsers({
      q,
      role: roleFilter,
      status: statusFilter,
      joined,
      sort,
      page: 1,
      pageSize: 2000,
    });
    const rows = ids.length
      ? result.rows.filter((u) => ids.includes(u.id))
      : result.rows;

    const sheet = usersExportSheet(rows);

    const { data: profile } = await supabase
      .from("profiles")
      .select("full_name")
      .eq("id", userId)
      .maybeSingle();

    const filterParts: string[] = [];
    if (q) filterParts.push(`Search: "${q}"`);
    if (roleFilter && roleFilter !== "all") filterParts.push(`Role: ${roleFilter}`);
    if (statusFilter && statusFilter !== "all") filterParts.push(`Status: ${statusFilter}`);
    if (joined !== "all") filterParts.push(`Joined: ${JOINED_RANGE_LABELS[joined]}`);

    const context: ExportContext = {
      title: "PTEC e-Library — Users",
      generatedAt: new Date(),
      lines: [
        ["Scope", ids.length ? `Selected users (${rows.length})` : `Filtered results (${rows.length})`],
        ["Filters", filterParts.length ? filterParts.join(" · ") : "None"],
        ["Sort", USER_SORT_LABELS[sort]],
        ["Generated by", profile?.full_name ? `${profile.full_name} (${callerRole})` : callerRole],
      ],
    };

    const body: BodyInit =
      format === "xlsx"
        ? new Blob([new Uint8Array(await buildWorkbook(context, [sheet])).buffer as ArrayBuffer])
        : sheetsToCsv([sheet]);

    // Audit the export (personal data leaving the system) — counts and filter
    // names only, never the exported values themselves.
    await supabase.from("admin_audit_log").insert({
      admin_id: userId,
      action: "users.export",
      target_table: "profiles",
      metadata: {
        format,
        rows: rows.length,
        scope: ids.length ? "selected" : "filtered",
        role: roleFilter || "all",
        status: statusFilter || "all",
        joined,
        hasSearch: Boolean(q),
      },
    });

    return new NextResponse(body, {
      headers: {
        "Content-Type": EXPORT_MIME[format],
        "Content-Disposition": `attachment; filename="${exportFilename("ptec-users", format)}"`,
        "Cache-Control": "private, no-store",
        "X-Export-Rows": String(rows.length),
      },
    });
  } catch (error) {
    if (isAdminAuthError(error)) {
      return NextResponse.json({ error: error.message }, { status: error.status });
    }
    console.error("[/api/admin/users/export]", error);
    return NextResponse.json({ error: "Export failed" }, { status: 500 });
  }
}
