import type { MetadataRoute } from "next";
import { getSiteConfig } from "@/lib/system-settings/config";
import { PWA_INK } from "@/lib/pwa/launch";

// The web app manifest, served at /manifest.webmanifest.
//
// This replaced a hand-maintained public/manifest.webmanifest so the installed
// app's name can never drift from the published System Settings identity the
// rest of the site renders (see lib/system-settings/config.ts). getSiteConfig()
// is unstable_cache'd with no cookies/headers, so this route still prerenders.
//
// LAUNCH COLOURS ARE NOT A FREE CHOICE. `background_color` is what Android
// paints behind the splash icon, and it must equal the first colour the app
// itself paints or the launch reads as a flash of the wrong app. That colour is
// PTEC ink (`.hero-ink`, #060B1A) — the navbar and hero are ink in BOTH light
// and dark themes, so one value is correct either way. The manifest previously
// said #ffffff, which is why every launch went white splash → near-black app.
export const dynamic = "force-static";

export default async function manifest(): Promise<MetadataRoute.Manifest> {
  const cfg = await getSiteConfig();

  return {
    // Stable identity: changing `id` makes Android treat this as a DIFFERENT
    // app and orphans every existing installation. It is pinned to the scope
    // and must never be derived from a setting an admin can edit.
    id: "/",
    name: cfg.seo.siteName,
    // Android truncates hard under the launcher icon, so prefer the
    // abbreviation ("PTEC") over the full library name.
    short_name: `${cfg.name.short} Library`,
    description: cfg.seo.siteDescription.en,

    // The canonical entry point. middleware.ts rewrites "/" to the /en segment
    // internally (no redirect), so a cold launch costs exactly one request.
    start_url: "/",
    scope: "/",
    display: "standalone",
    orientation: "portrait-primary",

    background_color: PWA_INK,
    theme_color: PWA_INK,

    lang: "en",
    dir: "ltr",
    categories: ["education", "books", "reference"],

    icons: [
      // "any" — shown unmasked (task switcher, desktop, install dialog). The
      // emblem is full-bleed and transparent here, which is correct for these
      // surfaces and wrong for a mask; hence the separate maskable pair below.
      {
        src: "/favicon/web-app-manifest-192x192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/favicon/web-app-manifest-512x512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      // "maskable" — opaque ink plate with the emblem inside Android's
      // 80%-diameter safe zone. Generated by scripts/generate-pwa-assets.mjs;
      // do not hand-edit or the safe-zone contract silently breaks.
      {
        src: "/favicon/icon-maskable-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/favicon/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],

    shortcuts: [
      { name: "Browse books", url: "/books" },
      { name: "Theses", url: "/theses" },
      { name: "Saved for offline", url: "/offline-books" },
    ],
  };
}
