import fs from "node:fs";
import path from "node:path";
import type { MetadataRoute } from "next";
import { getSiteConfig } from "@/lib/system-settings/config";
import { PWA_SPLASH, PWA_THEME_COLOR } from "@/lib/pwa/launch";

// Store-style screenshots for Chrome's richer install sheet on Android
// (web.dev/articles/web-apps/richer-install-ui): with at least one "narrow"
// screenshot, "Install app" opens an app-store-like sheet — name,
// description, swipeable screenshots — instead of a one-line prompt. Captured
// from production by `node scripts/capture-pwa-screenshots.mjs`; a file that
// is not on disk is left out, so the manifest never names a 404. Every one
// is 780×1688 (390×844 at 2×): one aspect ratio per form factor is a
// requirement, and 2.16:1 is inside the 2.3:1 limit. Never precached
// (lib/sw-policy.ts).
const SCREENSHOTS = [
  { file: "home.png", label: "Search every book, thesis and journal in the library" },
  { file: "books.png", label: "Browse the collection" },
  { file: "path.png", label: "Follow a learning path, step by step" },
] as const;

function installScreenshots(): NonNullable<MetadataRoute.Manifest["screenshots"]> {
  const dir = path.join(process.cwd(), "public", "pwa", "screenshots");
  return SCREENSHOTS.filter((shot) => fs.existsSync(path.join(dir, shot.file))).map((shot) => ({
    src: `/pwa/screenshots/${shot.file}`,
    sizes: "780x1688",
    type: "image/png",
    form_factor: "narrow" as const,
    label: shot.label,
  }));
}

// The web app manifest, served at /manifest.webmanifest.
//
// This replaced a hand-maintained public/manifest.webmanifest so the installed
// app's name can never drift from the published System Settings identity the
// rest of the site renders (see lib/system-settings/config.ts). getSiteConfig()
// is unstable_cache'd with no cookies/headers, so this route still prerenders.
//
// LAUNCH COLOURS ARE NOT A FREE CHOICE.
//
// `background_color` is what Android paints behind the splash icon, and it must
// equal what the PTEC startup screen paints or the launch flashes between two
// colours. Both are PWA_SPLASH (parchment) — see lib/pwa/launch.ts.
//
// `theme_color` is deliberately a DIFFERENT value: it drives the status bar,
// and THEME_INIT_SCRIPT re-points the theme-color meta to PWA_THEME_COLOR once
// the stored theme is known. Matching it here keeps the status bar one colour
// from the platform splash through to the app; setting it to the splash
// background instead produced a visible parchment-to-navy shift after launch.
export const dynamic = "force-static";

export default async function manifest(): Promise<MetadataRoute.Manifest> {
  const cfg = await getSiteConfig();

  return {
    // Stable identity: changing `id` makes Android treat this as a DIFFERENT
    // app and orphans every existing installation. It is pinned to the scope
    // and must never be derived from a setting an admin can edit.
    id: "/",
    name: cfg.seo.siteName,
    // Android truncates hard under the launcher icon, so prefer the
    // abbreviation ("PTEC") over the full library name.
    short_name: `${cfg.name.short} Library`,
    description: cfg.seo.siteDescription.en,

    // The canonical entry point. middleware.ts rewrites "/" to the /en segment
    // internally (no redirect), so a cold launch costs exactly one request.
    start_url: "/",
    scope: "/",
    display: "standalone",
    orientation: "portrait-primary",

    background_color: PWA_SPLASH,
    theme_color: PWA_THEME_COLOR,

    lang: "en",
    dir: "ltr",
    categories: ["education", "books", "reference"],

    icons: [
      // "any" — shown unmasked (task switcher, desktop, install dialog). The
      // emblem is full-bleed and transparent here, which is correct for these
      // surfaces and wrong for a mask; hence the separate maskable pair below.
      {
        src: "/favicon/web-app-manifest-192x192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/favicon/web-app-manifest-512x512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      // "maskable" — opaque ink plate with the emblem inside Android's
      // 80%-diameter safe zone. Generated by scripts/generate-pwa-assets.mjs;
      // do not hand-edit or the safe-zone contract silently breaks.
      {
        src: "/favicon/icon-maskable-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/favicon/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],

    screenshots: installScreenshots(),

    shortcuts: [
      { name: "Browse books", url: "/books" },
      { name: "Theses", url: "/theses" },
      { name: "Saved for offline", url: "/offline-books" },
    ],
  };
}
