import type { Metadata, Viewport } from "next";
import { SITE_URL } from "@/lib/seo/site";
import { defaultRobots } from "@/lib/seo/indexing";
import { getSiteConfig } from "@/lib/system-settings/config";
import { PWA_INK } from "@/lib/pwa/launch";

// Shared by every root layout (see components/layout/RootShell.tsx for why
// there is more than one). Page-level generateMetadata still overrides these.
//
// IDENTITY-FREE ON PURPOSE. The title, description, application name and Open
// Graph site name all come from the PUBLISHED system settings — they used to
// be string literals here, which is why publishing a new library name changed
// the footer but left every social share card and browser tab reading the
// compiled-in value. Use `identityMetadata()` below to layer them on; the
// only things that stay hard-coded are asset paths and the robots policy.
export const rootMetadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  icons: {
    // No SVG entry. /favicon/favicon.svg existed and browsers preferred it
    // (an image/svg+xml candidate wins over raster ones), but it was a 464 KB
    // base64 PNG wrapped in an <svg> — zero vector content, so it was strictly
    // a 464 KB way to render the same bitmap the 96px PNG below already
    // carries in 17 KB. It was fetched on every page load and precached by the
    // service worker. The file is deleted; do not re-add one unless it is
    // genuinely vector.
    icon: [
      { url: "/favicon.ico", sizes: "48x48" },
      { url: "/favicon/favicon-96x96.png", sizes: "96x96", type: "image/png" },
    ],
    apple: [
      { url: "/favicon/apple-touch-icon.png", sizes: "180x180", type: "image/png" },
    ],
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    alternateLocale: "km_KH",
    images: ["/og-default.png"],
  },
  twitter: {
    card: "summary_large_image",
  },
  // Environment-aware: hard noindex on previews/dev/staging, index only on
  // real production (lib/seo/indexing.ts). The public layout layers the
  // admin-managed kill switch on top; (admin)/(auth) layouts override to a
  // permanent noindex.
  robots: defaultRobots(),
  // Generated by app/manifest.ts (was a hand-maintained public/ file, which
  // let the installed app's name drift from the published site identity).
  manifest: "/manifest.webmanifest",
  // iOS has no manifest support worth relying on: standalone display, the
  // home-screen title and the status-bar treatment all come from these meta
  // tags instead. `black-translucent` lets the ink hero run under the status
  // bar, which is why every fixed surface pads with env(safe-area-inset-*).
  appleWebApp: {
    capable: true,
    title: "PTEC Library",
    statusBarStyle: "black-translucent",
  },
  other: {
    // Next 16 renders appleWebApp.capable as the standardised
    // `mobile-web-app-capable` only. Safari before iOS 15.4 reads exclusively
    // the apple-prefixed name, and without it those devices open the "installed"
    // app in a normal Safari tab — chrome, address bar and all.
    "apple-mobile-web-app-capable": "yes",
  },
};

/**
 * rootMetadata + the published organization identity, for the root layouts
 * that are dynamic anyway (auth, admin, offline shell, global 404).
 *
 * `locale` picks the site description; pass a `titleSuffix`-free title to use
 * the published site title as-is, or a `title` to render "<title> · <library>".
 */
export async function identityMetadata(
  locale: "en" | "km" = "en",
  title?: string,
): Promise<Metadata> {
  const cfg = await getSiteConfig();
  return {
    ...rootMetadata,
    title: title ? `${title} · ${cfg.libraryName.en}` : cfg.seo.siteTitle,
    description:
      locale === "km"
        ? cfg.seo.siteDescription.km
        : cfg.seo.siteDescription.en,
    applicationName: cfg.libraryName.en,
    openGraph: { ...rootMetadata.openGraph, siteName: cfg.seo.siteName },
  };
}

export const rootViewport: Viewport = {
  // Matches the manifest theme_color / background_color (lib/pwa/launch.ts) so
  // the Android splash, the status bar and the app's first painted pixel are
  // one colour. THEME_INIT_SCRIPT re-points this meta tag per theme once the
  // stored preference is known; this is only the pre-script value, and it must
  // be the launch colour rather than a lighter navy that reads as a flash.
  themeColor: PWA_INK,
  // Edge-to-edge on notched phones (esp. the installed PWA). Every fixed
  // surface must pad with env(safe-area-inset-*): navbar top, mobile drawer,
  // MobileBottomNav (already does).
  viewportFit: "cover",
};
