import { getRequestConfig } from 'next-intl/server';
import { cookies } from 'next/headers';
// Generated by the Next compiler from the root layouts' dynamic segments.
// app/[locale]/layout.tsx is a root layout, so `locale` is a root param.
import { locale as rootLocale } from 'next/root-params';
import { routing } from './routing';

type Locale = (typeof routing.locales)[number];

function isLocale(value: unknown): value is Locale {
  return routing.locales.includes(value as Locale);
}

export default getRequestConfig(async ({ requestLocale, locale }) => {
  // Resolution order matters for cacheability. Nothing here may read headers():
  // one headers() call in this path opts the ENTIRE public tree out of static
  // rendering, which is what used to make every page `private, no-store`.
  //
  //  1. `locale` — passed explicitly, e.g. getMessages({ locale }) in the root
  //     layouts. Free.
  //  2. `requestLocale` — next-intl's own mechanism, fed by setRequestLocale().
  //     UNRELIABLE HERE: it does not survive across route segments in this app's
  //     layout split (verified — getLocale() returned "en" on /km/home even
  //     immediately after setRequestLocale("km") in the same layout), so it is
  //     tried but never trusted as the last word.
  //  3. `rootLocale()` — the [locale] segment of the root layout, read as a
  //     route param. This is the one that actually carries the locale to server
  //     components like <Navbar>, and unlike headers() it is prerender-safe.
  //     Without it, every getTranslations() call in the public tree silently
  //     fell back to English and the whole Khmer site rendered in English.
  //  4. The ptec_locale cookie — reached ONLY on /admin and /auth, which sit
  //     outside the [locale] tree (rootLocale() is undefined there). cookies()
  //     is a dynamic API, but those routes are session-gated and dynamic anyway.
  let resolved: string | undefined = locale ?? (await requestLocale);

  if (!isLocale(resolved)) {
    resolved = await rootLocale();
  }

  if (!isLocale(resolved)) {
    const cookieLocale = (await cookies()).get('ptec_locale')?.value;
    resolved = isLocale(cookieLocale) ? cookieLocale : routing.defaultLocale;
  }

  return {
    locale: resolved,
    messages: (await import(`../messages/${resolved}.json`)).default,
    timeZone: 'Asia/Phnom_Penh',
  };
});
