// Builds the export bundle (sheets + report context) for the admin dashboard,
// honouring the same validated filters as the page. Shared by the CSV and
// XLSX formats of /api/admin/dashboard/export — the route stays a thin shell.

import "server-only";

import { defineSheet, type ExportContext, type ExportSheet } from "@/lib/export/core";
import type { DashboardFilters } from "@/lib/admin/dashboard-shared";
import {
  getOverviewData,
  getContentIntelligence,
  getSearchAiData,
  getAudienceData,
  getSystemData,
  CONTENT_PRESETS,
  type ContentPreset,
  type KpiDatum,
} from "@/lib/admin/intelligence";

export type DashboardExportBundle = {
  context: ExportContext;
  sheets: ExportSheet[];
  /** Filename base, e.g. "ptec-dashboard-overview". */
  baseName: string;
  /** Rows in the primary data sheet (for the success toast / audit log). */
  recordCount: number;
};

const RANGE_LABELS: Record<string, string> = {
  today: "Today",
  "7d": "Last 7 days",
  "30d": "Last 30 days",
  "90d": "Last 90 days",
};

function periodLabel(f: DashboardFilters): string {
  if (f.range === "custom" && f.from && f.to) return `${f.from} to ${f.to}`;
  return RANGE_LABELS[f.range] ?? f.range;
}

const TYPE_LABELS: Record<string, string> = {
  book: "Books",
  research_report: "Theses",
  publication: "Publications",
  post: "Posts",
};

function filtersLabel(f: DashboardFilters): string {
  const parts: string[] = [];
  if (f.type !== "all") parts.push(`Type: ${TYPE_LABELS[f.type] ?? f.type}`);
  if (f.dept) parts.push(`Department: ${f.dept}`);
  if (f.lang !== "all") parts.push(`Language: ${f.lang === "km" ? "Khmer" : "English"}`);
  return parts.length ? parts.join(" · ") : "None";
}

function buildContext(f: DashboardFilters, generatedBy: string | null): ExportContext {
  const lines: [string, string][] = [
    ["Period", periodLabel(f)],
    ["Filters", filtersLabel(f)],
    ["Comparison", f.compare ? "vs previous period" : "Off"],
  ];
  if (generatedBy) lines.push(["Generated by", generatedBy]);
  return {
    title: "PTEC e-Library — Admin Dashboard",
    lines,
    generatedAt: new Date(),
  };
}

type MetricRow = { metric: string; value: number | string | null };

const METRIC_COLUMNS = [
  { key: "metric", header: "Metric", value: (r: MetricRow) => r.metric },
  { key: "value", header: "Value", value: (r: MetricRow) => r.value, kind: "number" as const },
];

/** KPI rows with previous-period values and the dashboard's own change badge. */
type KpiRow = { metric: string; current: number | string | null; previous: number | string | null; change: string };

function kpiRow(metric: string, k: KpiDatum): KpiRow {
  return {
    metric,
    current: k.collecting ? "collecting" : k.value,
    previous: k.trend?.previous ?? null,
    change: k.trend && k.trend.mode !== "hidden" ? k.trend.value : "",
  };
}

export async function buildDashboardExport(
  filters: DashboardFilters,
  sp: Record<string, string>,
  generatedBy: string | null,
): Promise<DashboardExportBundle> {
  const context = buildContext(filters, generatedBy);

  switch (filters.view) {
    case "content": {
      const preset: ContentPreset = (CONTENT_PRESETS as readonly string[]).includes(sp.preset ?? "")
        ? (sp.preset as ContentPreset)
        : "top";
      // Export every matching row (not just the visible page) — the whole
      // catalog is a few hundred records.
      const data = await getContentIntelligence(filters, { page: 1, preset, pageSize: 10000 });
      const rows = data.rows;
      const sheet = defineSheet<(typeof rows)[number]>({
        name: "Content Performance",
        rows,
        columns: [
          { key: "title", header: "Title", value: (r) => r.title, width: 44 },
          { key: "type", header: "Type", value: (r) => TYPE_LABELS[r.type] ?? r.type },
          { key: "department", header: "Department", value: (r) => r.department },
          { key: "language", header: "Language", value: (r) => r.language },
          { key: "published", header: "Published", value: (r) => (r.published ? "yes" : "no") },
          { key: "views", header: "Views (period)", value: (r) => r.views, kind: "number" },
          { key: "uniqueViewers", header: "Unique viewers", value: (r) => r.uniqueViewers, kind: "number" },
          { key: "readerOpens", header: "Reader opens", value: (r) => r.readerOpens, kind: "number" },
          { key: "downloads", header: "Downloads", value: (r) => r.downloads, kind: "number" },
          { key: "conversionPct", header: "Conversion %", value: (r) => r.conversionPct, kind: "number" },
          { key: "delta", header: "Views delta vs prev", value: (r) => r.delta, kind: "number" },
          { key: "lifetimeViews", header: "Lifetime views", value: (r) => r.lifetimeViews, kind: "number" },
          { key: "completeness", header: "Metadata %", value: (r) => r.completeness, kind: "number" },
          { key: "updatedAt", header: "Updated", value: (r) => r.updatedAt, kind: "date" },
        ],
      });
      return { context, sheets: [sheet], baseName: "ptec-dashboard-content", recordCount: rows.length };
    }

    case "search": {
      const data = await getSearchAiData(filters);
      const metrics: MetricRow[] = [
        { metric: "Total searches", value: data.search.total },
        { metric: "Previous period searches", value: data.search.previousTotal },
        { metric: "Search sessions", value: data.search.sessions },
        { metric: "Click-through rate %", value: data.search.ctr },
        { metric: "Zero-result rate %", value: data.search.zeroRate },
        { metric: "Average results", value: data.search.avgResults },
        { metric: "Khmer share %", value: data.search.kmSharePct },
        { metric: "AI requests", value: data.ai.total },
        { metric: "AI success rate %", value: data.ai.okRate },
        { metric: "AI avg latency ms", value: data.ai.avgLatencyMs },
        { metric: "AI quota hits", value: data.ai.quotaHits },
      ];
      const queries = data.search.queryTable;
      const summarySheet = defineSheet<MetricRow>({ name: "Summary", rows: metrics, columns: METRIC_COLUMNS });
      const querySheet = defineSheet<(typeof queries)[number]>({
        name: "Search Queries",
        rows: queries,
        columns: [
          { key: "term", header: "Query", value: (r) => r.term, width: 36 },
          { key: "lang", header: "Language", value: (r) => r.lang },
          { key: "searches", header: "Searches", value: (r) => r.searches, kind: "number" },
          { key: "prevSearches", header: "Previous period", value: (r) => r.prevSearches, kind: "number" },
          { key: "avgResults", header: "Avg results", value: (r) => r.avgResults, kind: "number" },
          { key: "clicks", header: "Clicks", value: (r) => r.clicks, kind: "number" },
          { key: "ctrPct", header: "CTR %", value: (r) => r.ctrPct, kind: "number" },
          { key: "zero", header: "Zero result", value: (r) => (r.zero ? "yes" : "no") },
          { key: "suspectedTest", header: "Suspected test", value: (r) => (r.suspectedTest ? "yes" : "no") },
        ],
      });
      return {
        context,
        sheets: [summarySheet, querySheet],
        baseName: "ptec-dashboard-search",
        recordCount: queries.length,
      };
    }

    case "audience": {
      const data = await getAudienceData(filters);
      const metrics: MetricRow[] = [
        { metric: "New registrations", value: data.registrations.total },
        { metric: "Registered users (total)", value: data.totalUsers },
        { metric: "Active signed-in users", value: data.activeUsers.current },
        { metric: "Active signed-in users (previous)", value: data.activeUsers.previous },
        { metric: "Returning users", value: data.returningUsers },
        { metric: "Signed-in detail views", value: data.signedInViews },
        { metric: "Anonymous detail views", value: data.anonymousViews },
        { metric: "Views (English UI)", value: data.localeSplit.en },
        { metric: "Views (Khmer UI)", value: data.localeSplit.km },
        { metric: "Views (locale untracked)", value: data.localeSplit.unknown },
      ];
      const sheet = defineSheet<MetricRow>({ name: "Audience", rows: metrics, columns: METRIC_COLUMNS });
      return { context, sheets: [sheet], baseName: "ptec-dashboard-audience", recordCount: metrics.length };
    }

    case "system": {
      const data = await getSystemData(filters);
      const rows = data.appEvents;
      const sheet = defineSheet<(typeof rows)[number]>({
        name: "System Events",
        rows,
        columns: [
          { key: "kind", header: "Event kind", value: (r) => r.kind },
          { key: "total", header: "Total", value: (r) => r.total, kind: "number" },
          { key: "ok", header: "OK", value: (r) => r.ok, kind: "number" },
          { key: "errors", header: "Errors", value: (r) => r.errors, kind: "number" },
          { key: "fallbacks", header: "Fallbacks", value: (r) => r.fallbacks, kind: "number" },
          { key: "avgLatencyMs", header: "Avg latency ms", value: (r) => r.avgLatencyMs, kind: "number" },
        ],
      });
      return { context, sheets: [sheet], baseName: "ptec-dashboard-system", recordCount: rows.length };
    }

    default: {
      const data = await getOverviewData(filters);
      const kpis: KpiRow[] = [
        kpiRow("Unique visitors", data.kpis.uniqueVisitors),
        kpiRow("Content detail views", data.kpis.detailViews),
        kpiRow("Reader opens", data.kpis.readerOpens),
        kpiRow("Downloads", data.kpis.downloads),
        {
          metric: "Engagement conversion %",
          current: data.kpis.conversion.insufficient ? "insufficient data" : data.kpis.conversion.valuePct,
          previous: data.kpis.conversion.prevPct,
          change: "",
        },
        { metric: "Searches", current: data.discovery.volumes.searches, previous: data.discovery.prevVolumes.searches, change: "" },
        { metric: "Search result clicks", current: data.discovery.volumes.resultClicks, previous: data.discovery.prevVolumes.resultClicks, change: "" },
      ];
      const summarySheet = defineSheet<KpiRow>({
        name: "Summary",
        xlsxOnly: true,
        rows: kpis,
        columns: [
          { key: "metric", header: "Metric", value: (r) => r.metric, width: 30 },
          { key: "current", header: periodLabel(filters), value: (r) => r.current, kind: "number" },
          { key: "previous", header: "Previous period", value: (r) => r.previous, kind: "number" },
          { key: "change", header: "Change", value: (r) => r.change },
        ],
      });
      const daily = data.engagement.series.views.map((p, i) => ({
        date: p.date,
        views: p.value,
        visitors: data.engagement.series.visitors[i]?.value ?? 0,
        readerOpens: data.engagement.series.readerOpens?.[i]?.value ?? null,
        downloads: data.engagement.series.downloads[i]?.value ?? 0,
      }));
      const dailySheet = defineSheet<(typeof daily)[number]>({
        name: data.granularity === "hour" ? "Hourly Activity" : "Daily Activity",
        rows: daily,
        columns: [
          {
            key: "date",
            header: data.granularity === "hour" ? "Hour" : "Date",
            value: (r) => r.date,
            kind: data.granularity === "hour" ? "string" : "date",
            width: 14,
          },
          { key: "views", header: "Content detail views", value: (r) => r.views, kind: "number" },
          { key: "visitors", header: "Unique visitors", value: (r) => r.visitors, kind: "number" },
          { key: "readerOpens", header: "Reader opens", value: (r) => r.readerOpens, kind: "number" },
          { key: "downloads", header: "Downloads", value: (r) => r.downloads, kind: "number" },
        ],
      });
      return {
        context,
        sheets: [summarySheet, dailySheet],
        baseName: "ptec-dashboard-overview",
        recordCount: daily.length,
      };
    }
  }
}
