-- 0118_homepage_photos.sql
-- ─────────────────────────────────────────────────────────────────────────────
-- Admin-managed homepage photo gallery.
--
-- The homepage hero photo has always been a build-time asset (public/hero/*,
-- immutable-cached, regenerated by scripts/optimize-hero.mjs). That is right
-- for the LCP image and wrong for everything else: showing what the library
-- actually looks like — students at the carrels, a reading session, an event —
-- is editorial content that changes every term, and it should not need a
-- deploy. This table is that editorial surface.
--
-- It deliberately does NOT replace public/hero/*. The hero background stays a
-- pre-generated local variant set (see the HERO_SIZES comment in the homepage)
-- because it is the LCP element and a remote, admin-uploadable URL cannot be
-- preloaded at build time. These photos render BELOW the hero.
--
-- RLS: anonymous visitors may read active rows only. There is deliberately NO
-- write policy — every mutation goes through a Server Action holding the
-- service-role key and re-checking requirePermission('homepage_photos',
-- 'write'). A blanket `for all to authenticated using (true)` would let any
-- signed-up reader delete the homepage, since `authenticated` on this project
-- includes every self-registered library member.
--
-- Rollback (manual; also orphans the uploaded files in Zima Storage, which are
-- then removable from /admin/storage):
--   drop table if exists public.homepage_photos;
--   delete from public.role_permissions where resource = 'homepage_photos';
-- ─────────────────────────────────────────────────────────────────────────────

create table if not exists public.homepage_photos (
  id            uuid primary key default gen_random_uuid(),
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),

  -- Storage. `public_url` is the canonical reference the app renders and the
  -- key `zimaDelete()` needs; `storage_key` keeps the human-readable object
  -- path ("homepage/uuid-name.webp") so a row can still be matched to a file
  -- in /admin/storage if the CDN hostname ever changes.
  storage_key   text not null,
  public_url    text not null,

  -- Intrinsic dimensions of the stored (already optimised) file. next/image
  -- needs width/height to reserve space; without them the gallery shifts
  -- layout as each photo decodes. Nullable because sharp can fail to report
  -- them for an exotic input and a missing number must not block an upload.
  width         integer,
  height        integer,
  -- Tiny base64 WebP (~20x13px) used as next/image's blurDataURL.
  blur_data_url text,

  display_order integer not null default 0,
  is_active     boolean not null default true,

  -- Bilingual captions (optional) and alt text (required by the admin form,
  -- nullable here so a future importer is not blocked mid-backfill).
  caption_km    text,
  caption_en    text,
  alt_text_km   text,
  alt_text_en   text,

  category      text not null default 'general'
    check (category in ('general', 'ptec-library', 'o-bek-kaom', 'events')),

  -- Uploader attribution. References profiles (not auth.users) so the admin
  -- table can join a name without touching the auth schema.
  uploaded_by   uuid references public.profiles(id) on delete set null
);

comment on table public.homepage_photos is
  'Admin-managed photos shown in the homepage "life at the library" gallery. Read publicly (active rows only) via lib/homepage-photos.ts; written only by service-role Server Actions.';

-- The public read is always "active photos, in display order" — one composite
-- index covers it. The second supports the admin category filter.
create index if not exists idx_homepage_photos_active_order
  on public.homepage_photos (is_active, display_order, created_at);
create index if not exists idx_homepage_photos_category
  on public.homepage_photos (category);

-- Reuses the generic touch function from the initial schema rather than
-- defining another set_updated_at(): a second generic name would be one
-- `create or replace` away from silently rewriting the shared one.
drop trigger if exists homepage_photos_set_updated_at on public.homepage_photos;
create trigger homepage_photos_set_updated_at
  before update on public.homepage_photos
  for each row execute function public.touch_updated_at();

-- ── RLS ──────────────────────────────────────────────────────────────────────
alter table public.homepage_photos enable row level security;

drop policy if exists "Public can view active homepage photos" on public.homepage_photos;
create policy "Public can view active homepage photos"
  on public.homepage_photos
  for select
  using (is_active = true);

-- SELECT privilege is what lets the policy above be consulted at all; the
-- policy still decides the rows (same reasoning as 0117).
revoke all on public.homepage_photos from public;
grant select on public.homepage_photos to anon, authenticated;
grant all    on public.homepage_photos to service_role;

-- ── Permissions ──────────────────────────────────────────────────────────────
-- Mirrors DEFAULT_PERMISSIONS in lib/permissions.ts — keep both in sync.
-- Modelled on `posts`/`announcements`: this is editorial content about the
-- library, not a security-sensitive setting, so the roles that already publish
-- public-facing content can manage it.
insert into public.role_permissions (role, resource, level)
values
  ('reader',      'homepage_photos', 'none'),
  ('staff',       'homepage_photos', 'write'),
  ('librarian',   'homepage_photos', 'write'),
  ('admin',       'homepage_photos', 'write'),
  ('super_admin', 'homepage_photos', 'write')
on conflict (role, resource) do nothing;
