-- 0147_composite_author_split.sql
--
-- Gives each person named inside a composite `authors` row their own record
-- and their own credit, so three scholars sharing one URL become three
-- scholars with three URLs.
--
-- GENERATED by scripts/generate-composite-split-migration.ts from the shipped
-- normalizeByline(), its extracted ROLE, and authorSlug(). Do not hand-edit:
-- regenerate. The split rule is intricate (whole-string identity first, then
-- splitByline(), refusing to separate what it cannot separate safely) and a
-- PL/pgSQL copy would drift from the one the application reads with — the same
-- call 0130 made for normalizeTitle() and 0146 made for subject matching.
--
-- EVERY statement is gated on the composite existing in this database, so a
-- database without these rows (the CI seed) is left completely untouched
-- rather than gaining 113 authors with no works.
--
-- `books.author_id` IS NOT TOUCHED. It is a single foreign key, so a book with
-- three authors can only point at one of them; "reassigning" it would destroy
-- two thirds of what it records. The many-to-many credit belongs in
-- `resource_contributors`, which is what that table is for.
--
-- Derived on 2026-09-14 from 43 composite row(s):
--   113 new author record(s), 131 credit edge(s), role as the byline states it.

-- A split-derived contributor is neither a librarian's keystroke ('manual')
-- nor a raw 0105 backfill ('authors'): it is derived from one. Recording that
-- honestly needs its own source value, and the CHECK has to allow it.
-- kindOfCanonicalRow() believes a stored 'person' only for 'manual', so these
-- rows are re-classified from the name on read — which for a single clean
-- name is a no-op, and is the safe direction regardless.
ALTER TABLE public.contributors DROP CONSTRAINT IF EXISTS contributors_source_check;
ALTER TABLE public.contributors ADD CONSTRAINT contributors_source_check
  CHECK (source IN ('manual', 'authors', 'publication_authors', 'thesis_text',
                    'thesis_advisor', 'composite_split'));

-- The split, as data: which composite names whom, in which order, in what role.
--
-- A session-scoped temp table with explicit drops, NOT `ON COMMIT DROP`: that
-- form needs the caller to have opened a transaction, and while production's
-- applier does (infra/supabase/scripts/migrate.sh uses --single-transaction),
-- a plain `psql < file` on the box does not — the table would be dropped the
-- instant it was created, and the next statement fails on a relation that does
-- not exist. Depending on the caller's transaction mode is not a property this
-- file should have.
DROP TABLE IF EXISTS composite_split;
CREATE TEMP TABLE composite_split (composite text, person text, slug text, role text, seq integer);
INSERT INTO composite_split (composite, person, slug, role, seq) VALUES
    ('Oon-Seng Tan, Woon-Chia Liu, Ee-Ling Low (Editors)', 'Oon-Seng Tan', 'oon-seng-tan', 'editor', 0),
    ('Oon-Seng Tan, Woon-Chia Liu, Ee-Ling Low (Editors)', 'Woon-Chia Liu', 'woon-chia-liu', 'editor', 1),
    ('Oon-Seng Tan, Woon-Chia Liu, Ee-Ling Low (Editors)', 'Ee-Ling Low', 'ee-ling-low', 'editor', 2),
    ('Marguerite G. Lodico, Dean T. Spaulding, Katherine H. Voegtle', 'Marguerite G. Lodico', 'marguerite-g-lodico', 'author', 0),
    ('Marguerite G. Lodico, Dean T. Spaulding, Katherine H. Voegtle', 'Dean T. Spaulding', 'dean-t-spaulding', 'author', 1),
    ('Marguerite G. Lodico, Dean T. Spaulding, Katherine H. Voegtle', 'Katherine H. Voegtle', 'katherine-h-voegtle', 'author', 2),
    ('Stephen Howe, Kristina Henriksson', 'Stephen Howe', 'stephen-howe', 'author', 0),
    ('Stephen Howe, Kristina Henriksson', 'Kristina Henriksson', 'kristina-henriksson', 'author', 1),
    ('John W. Creswell, Cheryl N. Poth', 'John W. Creswell', 'john-w-creswell', 'author', 0),
    ('John W. Creswell, Cheryl N. Poth', 'Cheryl N. Poth', 'cheryl-n-poth', 'author', 1),
    ('David Evans, Paul Gruba, Justin Zobel', 'David Evans', 'david-evans', 'author', 0),
    ('David Evans, Paul Gruba, Justin Zobel', 'Paul Gruba', 'paul-gruba', 'author', 1),
    ('David Evans, Paul Gruba, Justin Zobel', 'Justin Zobel', 'justin-zobel', 'author', 2),
    ('Stephen Kemmis, Robin McTaggart, Rhonda Nixon', 'Stephen Kemmis', 'stephen-kemmis', 'author', 0),
    ('Stephen Kemmis, Robin McTaggart, Rhonda Nixon', 'Robin McTaggart', 'robin-mctaggart', 'author', 1),
    ('Stephen Kemmis, Robin McTaggart, Rhonda Nixon', 'Rhonda Nixon', 'rhonda-nixon', 'author', 2),
    ('Bert P.M. Creemers, Leonidas Kyriakides, Pam Sammons (Editors)', 'Bert P.M. Creemers', 'bert-p-m-creemers', 'editor', 0),
    ('Bert P.M. Creemers, Leonidas Kyriakides, Pam Sammons (Editors)', 'Leonidas Kyriakides', 'leonidas-kyriakides', 'editor', 1),
    ('Bert P.M. Creemers, Leonidas Kyriakides, Pam Sammons (Editors)', 'Pam Sammons', 'pam-sammons', 'editor', 2),
    ('Kenneth N. Berk, Patrick Carey', 'Kenneth N. Berk', 'kenneth-n-berk', 'author', 0),
    ('Kenneth N. Berk, Patrick Carey', 'Patrick Carey', 'patrick-carey', 'author', 1),
    ('Sara Efrat Efron, Ruth Ravid', 'Sara Efrat Efron', 'sara-efrat-efron', 'author', 0),
    ('Sara Efrat Efron, Ruth Ravid', 'Ruth Ravid', 'ruth-ravid', 'author', 1),
    ('K. B. Everard, Geoffrey Morris, Ian Wilson', 'K. B. Everard', 'k-b-everard', 'author', 0),
    ('K. B. Everard, Geoffrey Morris, Ian Wilson', 'Geoffrey Morris', 'geoffrey-morris', 'author', 1),
    ('K. B. Everard, Geoffrey Morris, Ian Wilson', 'Ian Wilson', 'ian-wilson', 'author', 2),
    ('Ernest T. Stringer, Lois McFadyen Christensen, Shelia C. Baldwin', 'Ernest T. Stringer', 'ernest-t-stringer', 'author', 0),
    ('Ernest T. Stringer, Lois McFadyen Christensen, Shelia C. Baldwin', 'Lois McFadyen Christensen', 'lois-mcfadyen-christensen', 'author', 1),
    ('Ernest T. Stringer, Lois McFadyen Christensen, Shelia C. Baldwin', 'Shelia C. Baldwin', 'shelia-c-baldwin', 'author', 2),
    ('Gloria Ladson-Billings, William F. Tate (Editors)', 'Gloria Ladson-Billings', 'gloria-ladson-billings', 'editor', 0),
    ('Gloria Ladson-Billings, William F. Tate (Editors)', 'William F. Tate', 'william-f-tate', 'editor', 1),
    ('Stephen D. Lapan, MaryLynn T. Quartaroli, Frances Julia Riemer (Editors)', 'Stephen D. Lapan', 'stephen-d-lapan', 'editor', 0),
    ('Stephen D. Lapan, MaryLynn T. Quartaroli, Frances Julia Riemer (Editors)', 'MaryLynn T. Quartaroli', 'marylynn-t-quartaroli', 'editor', 1),
    ('Stephen D. Lapan, MaryLynn T. Quartaroli, Frances Julia Riemer (Editors)', 'Frances Julia Riemer', 'frances-julia-riemer', 'editor', 2),
    ('Geoffrey E. Mills, L. R. Gay', 'Geoffrey E. Mills', 'geoffrey-e-mills', 'author', 0),
    ('Geoffrey E. Mills, L. R. Gay', 'L. R. Gay', 'l-r-gay', 'author', 1),
    ('Donald Ary, Lucy Cheser Jacobs, Chris Sorensen', 'Donald Ary', 'donald-ary', 'author', 0),
    ('Donald Ary, Lucy Cheser Jacobs, Chris Sorensen', 'Lucy Cheser Jacobs', 'lucy-cheser-jacobs', 'author', 1),
    ('Donald Ary, Lucy Cheser Jacobs, Chris Sorensen', 'Chris Sorensen', 'chris-sorensen', 'author', 2),
    ('John Flowerdew, Pejman Habibie', 'John Flowerdew', 'john-flowerdew', 'author', 0),
    ('John Flowerdew, Pejman Habibie', 'Pejman Habibie', 'pejman-habibie', 'author', 1),
    ('Stephen Gorard, Chris Taylor', 'Stephen Gorard', 'stephen-gorard', 'author', 0),
    ('Stephen Gorard, Chris Taylor', 'Chris Taylor', 'chris-taylor', 'author', 1),
    ('Alan Crawford, Wendy Saul, Samuel R. Mathews, James Makinster', 'Alan Crawford', 'alan-crawford', 'author', 0),
    ('Alan Crawford, Wendy Saul, Samuel R. Mathews, James Makinster', 'Wendy Saul', 'wendy-saul', 'author', 1),
    ('Alan Crawford, Wendy Saul, Samuel R. Mathews, James Makinster', 'Samuel R. Mathews', 'samuel-r-mathews', 'author', 2),
    ('Alan Crawford, Wendy Saul, Samuel R. Mathews, James Makinster', 'James Makinster', 'james-makinster', 'author', 3),
    ('Pat Bazeley, Kristi Jackson', 'Pat Bazeley', 'pat-bazeley', 'author', 0),
    ('Pat Bazeley, Kristi Jackson', 'Kristi Jackson', 'kristi-jackson', 'author', 1),
    ('Robert H. Carver, Jane Gradwohl Nash', 'Robert H. Carver', 'robert-h-carver', 'author', 0),
    ('Robert H. Carver, Jane Gradwohl Nash', 'Jane Gradwohl Nash', 'jane-gradwohl-nash', 'author', 1),
    ('David Scott, Marlene Morrison', 'David Scott', 'david-scott', 'author', 0),
    ('David Scott, Marlene Morrison', 'Marlene Morrison', 'marlene-morrison', 'author', 1),
    ('R. Burke Johnson, Larry Christensen', 'R. Burke Johnson', 'r-burke-johnson', 'author', 0),
    ('R. Burke Johnson, Larry Christensen', 'Larry Christensen', 'larry-christensen', 'author', 1),
    ('Louis Cohen, Lawrence Manion, Keith Morrison', 'Louis Cohen', 'louis-cohen', 'author', 0),
    ('Louis Cohen, Lawrence Manion, Keith Morrison', 'Lawrence Manion', 'lawrence-manion', 'author', 1),
    ('Louis Cohen, Lawrence Manion, Keith Morrison', 'Keith Morrison', 'keith-morrison', 'author', 2),
    ('វង់ សុធារ៉ា, ណុប សុខា', 'វង់ សុធារ៉ា', 'វង់-សុធារ៉ា', 'author', 0),
    ('វង់ សុធារ៉ា, ណុប សុខា', 'ណុប សុខា', 'ណុប-សុខា', 'author', 1),
    ('Suzanne Choo, Deb Sawch, Alison Villanueva, Ruth Vinz (Editors)', 'Suzanne Choo', 'suzanne-choo', 'editor', 0),
    ('Suzanne Choo, Deb Sawch, Alison Villanueva, Ruth Vinz (Editors)', 'Deb Sawch', 'deb-sawch', 'editor', 1),
    ('Suzanne Choo, Deb Sawch, Alison Villanueva, Ruth Vinz (Editors)', 'Alison Villanueva', 'alison-villanueva', 'editor', 2),
    ('Suzanne Choo, Deb Sawch, Alison Villanueva, Ruth Vinz (Editors)', 'Ruth Vinz', 'ruth-vinz', 'editor', 3),
    ('Ronghuai Huang, J. Michael Spector, Junfeng Yang', 'Ronghuai Huang', 'ronghuai-huang', 'author', 0),
    ('Ronghuai Huang, J. Michael Spector, Junfeng Yang', 'J. Michael Spector', 'j-michael-spector', 'author', 1),
    ('Ronghuai Huang, J. Michael Spector, Junfeng Yang', 'Junfeng Yang', 'junfeng-yang', 'author', 2),
    ('Bill Atweh, Stephen Kemmis, Patricia Weeks (Editors)', 'Bill Atweh', 'bill-atweh', 'editor', 0),
    ('Bill Atweh, Stephen Kemmis, Patricia Weeks (Editors)', 'Stephen Kemmis', 'stephen-kemmis', 'editor', 1),
    ('Bill Atweh, Stephen Kemmis, Patricia Weeks (Editors)', 'Patricia Weeks', 'patricia-weeks', 'editor', 2),
    ('Matthew B. Miles, A. Michael Huberman, Johnny Saldaña', 'Matthew B. Miles', 'matthew-b-miles', 'author', 0),
    ('Matthew B. Miles, A. Michael Huberman, Johnny Saldaña', 'A. Michael Huberman', 'a-michael-huberman', 'author', 1),
    ('Matthew B. Miles, A. Michael Huberman, Johnny Saldaña', 'Johnny Saldaña', 'johnny-saldaña', 'author', 2),
    ('ង៉ែត រ៉ាប៊ី, នាង សារិន', 'ង៉ែត រ៉ាប៊ី', 'ង៉ែត-រ៉ាប៊ី', 'author', 0),
    ('ង៉ែត រ៉ាប៊ី, នាង សារិន', 'នាង សារិន', 'នាង-សារិន', 'author', 1),
    ('Young Hoan Cho, Imelda S. Caleon, Manu Kapur (Editors)', 'Young Hoan Cho', 'young-hoan-cho', 'editor', 0),
    ('Young Hoan Cho, Imelda S. Caleon, Manu Kapur (Editors)', 'Imelda S. Caleon', 'imelda-s-caleon', 'editor', 1),
    ('Young Hoan Cho, Imelda S. Caleon, Manu Kapur (Editors)', 'Manu Kapur', 'manu-kapur', 'editor', 2),
    ('Maree Gosper, Dirk Ifenthaler (Editors)', 'Maree Gosper', 'maree-gosper', 'editor', 0),
    ('Maree Gosper, Dirk Ifenthaler (Editors)', 'Dirk Ifenthaler', 'dirk-ifenthaler', 'editor', 1),
    ('Valerie Hill-Jackson, Chance W. Lewis (Editors)', 'Valerie Hill-Jackson', 'valerie-hill-jackson', 'editor', 0),
    ('Valerie Hill-Jackson, Chance W. Lewis (Editors)', 'Chance W. Lewis', 'chance-w-lewis', 'editor', 1),
    ('Ron White, Andy Hockley, Julie van der Horst Jansen, Melissa S. Laughner', 'Ron White', 'ron-white', 'author', 0),
    ('Ron White, Andy Hockley, Julie van der Horst Jansen, Melissa S. Laughner', 'Andy Hockley', 'andy-hockley', 'author', 1),
    ('Ron White, Andy Hockley, Julie van der Horst Jansen, Melissa S. Laughner', 'Julie van der Horst Jansen', 'julie-van-der-horst-jansen', 'author', 2),
    ('Ron White, Andy Hockley, Julie van der Horst Jansen, Melissa S. Laughner', 'Melissa S. Laughner', 'melissa-s-laughner', 'author', 3),
    ('Steven J. Taylor, Robert Bogdan, Marjorie L. DeVault', 'Steven J. Taylor', 'steven-j-taylor', 'author', 0),
    ('Steven J. Taylor, Robert Bogdan, Marjorie L. DeVault', 'Robert Bogdan', 'robert-bogdan', 'author', 1),
    ('Steven J. Taylor, Robert Bogdan, Marjorie L. DeVault', 'Marjorie L. DeVault', 'marjorie-l-devault', 'author', 2),
    ('ខាំ សុមករា, គង់ ប៊ុនធី, ប៊ុន ស្រុង, លីន ញ៉ក់, ឡាយ រតនា, ឡាយ ណូរ៉ា', 'ខាំ សុមករា', 'ខាំ-សុមករា', 'author', 0),
    ('ខាំ សុមករា, គង់ ប៊ុនធី, ប៊ុន ស្រុង, លីន ញ៉ក់, ឡាយ រតនា, ឡាយ ណូរ៉ា', 'គង់ ប៊ុនធី', 'គង់-ប៊ុនធី', 'author', 1),
    ('ខាំ សុមករា, គង់ ប៊ុនធី, ប៊ុន ស្រុង, លីន ញ៉ក់, ឡាយ រតនា, ឡាយ ណូរ៉ា', 'ប៊ុន ស្រុង', 'ប៊ុន-ស្រុង', 'author', 2),
    ('ខាំ សុមករា, គង់ ប៊ុនធី, ប៊ុន ស្រុង, លីន ញ៉ក់, ឡាយ រតនា, ឡាយ ណូរ៉ា', 'លីន ញ៉ក់', 'លីន-ញ៉ក់', 'author', 3),
    ('ខាំ សុមករា, គង់ ប៊ុនធី, ប៊ុន ស្រុង, លីន ញ៉ក់, ឡាយ រតនា, ឡាយ ណូរ៉ា', 'ឡាយ រតនា', 'ឡាយ-រតនា', 'author', 4),
    ('ខាំ សុមករា, គង់ ប៊ុនធី, ប៊ុន ស្រុង, លីន ញ៉ក់, ឡាយ រតនា, ឡាយ ណូរ៉ា', 'ឡាយ ណូរ៉ា', 'ឡាយ-ណូរ៉ា', 'author', 5),
    ('ផេង ពង្សរ៉ាស៊ី, ដេវីដ ឆេនដល័រ, គ្រីស្តូហ្វ័រ ឌៀរីង, សុភ័ក្ត្រ ភាណា', 'ផេង ពង្សរ៉ាស៊ី', 'ផេង-ពង្សរ៉ាស៊ី', 'author', 0),
    ('ផេង ពង្សរ៉ាស៊ី, ដេវីដ ឆេនដល័រ, គ្រីស្តូហ្វ័រ ឌៀរីង, សុភ័ក្ត្រ ភាណា', 'ដេវីដ ឆេនដល័រ', 'ដេវីដ-ឆេនដល័រ', 'author', 1),
    ('ផេង ពង្សរ៉ាស៊ី, ដេវីដ ឆេនដល័រ, គ្រីស្តូហ្វ័រ ឌៀរីង, សុភ័ក្ត្រ ភាណា', 'គ្រីស្តូហ្វ័រ ឌៀរីង', 'គ្រីស្តូហ្វ័រ-ឌៀរីង', 'author', 2),
    ('ផេង ពង្សរ៉ាស៊ី, ដេវីដ ឆេនដល័រ, គ្រីស្តូហ្វ័រ ឌៀរីង, សុភ័ក្ត្រ ភាណា', 'សុភ័ក្ត្រ ភាណា', 'សុភ័ក្ត្រ-ភាណា', 'author', 3),
    ('Richard L. Scheaffer, William Mendenhall III, R. Lyman Ott, Kenneth G. Gerow', 'Richard L. Scheaffer', 'richard-l-scheaffer', 'author', 0),
    ('Richard L. Scheaffer, William Mendenhall III, R. Lyman Ott, Kenneth G. Gerow', 'William Mendenhall III', 'william-mendenhall-iii', 'author', 1),
    ('Richard L. Scheaffer, William Mendenhall III, R. Lyman Ott, Kenneth G. Gerow', 'R. Lyman Ott', 'r-lyman-ott', 'author', 2),
    ('Richard L. Scheaffer, William Mendenhall III, R. Lyman Ott, Kenneth G. Gerow', 'Kenneth G. Gerow', 'kenneth-g-gerow', 'author', 3),
    ('Leonard A. Jason, David S. Glenwick (Editors)', 'Leonard A. Jason', 'leonard-a-jason', 'editor', 0),
    ('Leonard A. Jason, David S. Glenwick (Editors)', 'David S. Glenwick', 'david-s-glenwick', 'editor', 1),
    ('Donna Kalmbach Phillips, Kevin Carr', 'Donna Kalmbach Phillips', 'donna-kalmbach-phillips', 'author', 0),
    ('Donna Kalmbach Phillips, Kevin Carr', 'Kevin Carr', 'kevin-carr', 'author', 1),
    ('L. R. Gay, Geoffrey E. Mills, Peter Airasian', 'L. R. Gay', 'l-r-gay', 'author', 0),
    ('L. R. Gay, Geoffrey E. Mills, Peter Airasian', 'Geoffrey E. Mills', 'geoffrey-e-mills', 'author', 1),
    ('L. R. Gay, Geoffrey E. Mills, Peter Airasian', 'Peter Airasian', 'peter-airasian', 'author', 2),
    ('Geoffrey R. Marczyk, David DeMatteo, David Festinger', 'Geoffrey R. Marczyk', 'geoffrey-r-marczyk', 'author', 0),
    ('Geoffrey R. Marczyk, David DeMatteo, David Festinger', 'David DeMatteo', 'david-dematteo', 'author', 1),
    ('Geoffrey R. Marczyk, David DeMatteo, David Festinger', 'David Festinger', 'david-festinger', 'author', 2),
    ('Perry R. Hinton, Charlotte Brownlow, Isabella McMurray, Bob Cozens', 'Perry R. Hinton', 'perry-r-hinton', 'author', 0),
    ('Perry R. Hinton, Charlotte Brownlow, Isabella McMurray, Bob Cozens', 'Charlotte Brownlow', 'charlotte-brownlow', 'author', 1),
    ('Perry R. Hinton, Charlotte Brownlow, Isabella McMurray, Bob Cozens', 'Isabella McMurray', 'isabella-mcmurray', 'author', 2),
    ('Perry R. Hinton, Charlotte Brownlow, Isabella McMurray, Bob Cozens', 'Bob Cozens', 'bob-cozens', 'author', 3),
    ('Jack R. Fraenkel, Norman E. Wallen, Helen H. Hyun', 'Jack R. Fraenkel', 'jack-r-fraenkel', 'author', 0),
    ('Jack R. Fraenkel, Norman E. Wallen, Helen H. Hyun', 'Norman E. Wallen', 'norman-e-wallen', 'author', 1),
    ('Jack R. Fraenkel, Norman E. Wallen, Helen H. Hyun', 'Helen H. Hyun', 'helen-h-hyun', 'author', 2);

-- ── 1. One authors row per person, only where the composite is present ──────
-- authors_slug_key is a PARTIAL unique index (where slug is not null), so the
-- conflict target must repeat its predicate or Postgres cannot infer it.
INSERT INTO public.authors (name, slug)
SELECT DISTINCT s.person, s.slug
  FROM composite_split s
 WHERE EXISTS (SELECT 1 FROM public.authors a WHERE a.name = s.composite)
ON CONFLICT (slug) WHERE slug IS NOT NULL DO NOTHING;

-- ── 2. One contributors row per person, linked to its authors row ───────────
INSERT INTO public.contributors (display_name, contributor_type, source, legacy_author_id)
SELECT DISTINCT a.name, 'person', 'composite_split', a.id
  FROM composite_split s
  JOIN public.authors a ON a.slug = s.slug
 WHERE EXISTS (SELECT 1 FROM public.authors c WHERE c.name = s.composite)
   AND NOT EXISTS (SELECT 1 FROM public.contributors c2 WHERE c2.legacy_author_id = a.id);

-- ── 3. Credit each person on every book their composite is attached to ──────
-- sequence follows byline order; role is the one the byline STATES, so an
-- edited volume credits editors rather than authors.
INSERT INTO public.resource_contributors (resource_type, resource_id, contributor_id, role, sequence)
SELECT 'book', b.id, c.id, s.role, s.seq
  FROM composite_split s
  JOIN public.authors ca ON ca.name = s.composite
  JOIN public.books b ON b.author_id = ca.id
  JOIN public.authors pa ON pa.slug = s.slug
  JOIN public.contributors c ON c.legacy_author_id = pa.id
ON CONFLICT (resource_type, resource_id, contributor_id, role) DO NOTHING;

DROP TABLE IF EXISTS composite_split;

-- ── 4. Report ───────────────────────────────────────────────────────────────
DO $$
DECLARE v_people integer; v_edges integer;
BEGIN
  SELECT count(*) INTO v_people FROM public.contributors WHERE source = 'composite_split';
  SELECT count(*) INTO v_edges FROM public.resource_contributors rc
    JOIN public.contributors c ON c.id = rc.contributor_id WHERE c.source = 'composite_split';
  RAISE NOTICE '0147: % split contributor(s), % credit edge(s)', v_people, v_edges;
END $$;
